pipeline:

  test:
    image: ethicaljobs/aphex
    pull: true
    commands: [ 
      'sleep 15',
      'composer install --prefer-dist', 
      './vendor/bin/phpunit' 
    ]
    environment:
      - ES_HOST=elasticsearch:9200

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments
    when:
      event: tag

services:
  elasticsearch:
    image: elasticsearch:5-alpine  